import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import initSqlJs, { type Database } from 'sql.js';
import worker, { type CloudflareEnv } from '../apps/cloudflare/src/index.js';

const ADMIN_ID='00000000-0000-4000-8000-000000000001';
const STAFF_ID='00000000-0000-4000-8000-000000000002';
const ADMIN_TOKEN='cf28-admin-session-token';
const STAFF_TOKEN='cf28-staff-session-token';
async function sha256(value:string):Promise<string>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
class SqlStatement{private values:unknown[]=[];constructor(private readonly database:Database,private readonly sql:string){}bind(...values:unknown[]):SqlStatement{this.values=values;return this;}async first<T>():Promise<T|null>{const statement=this.database.prepare(this.sql);try{statement.bind(this.values as any[]);return statement.step()?statement.getAsObject() as T:null;}finally{statement.free();}}async all<T>():Promise<{results:T[]}>{const statement=this.database.prepare(this.sql);const results:T[]=[];try{statement.bind(this.values as any[]);while(statement.step())results.push(statement.getAsObject() as T);return{results};}finally{statement.free();}}async run():Promise<{success:boolean;meta:{changes:number;last_row_id:number}}>{this.database.run(this.sql,this.values as any[]);return{success:true,meta:{changes:this.database.getRowsModified(),last_row_id:0}};}}
class SqlD1{constructor(readonly database:Database){}prepare(sql:string):SqlStatement{return new SqlStatement(this.database,sql);}async batch(statements:SqlStatement[]):Promise<unknown[]>{this.database.run('BEGIN IMMEDIATE');try{const results=[];for(const statement of statements)results.push(await statement.run());this.database.run('COMMIT');return results;}catch(error){this.database.run('ROLLBACK');throw error;}}}
const migration=(name:string)=>readFileSync(join(process.cwd(),'apps','cloudflare','migrations',name),'utf8');
const request=(path:string,token:string,init:RequestInit={})=>{const headers=new Headers(init.headers);headers.set('X-Session-Token',token);if(init.body)headers.set('Content-Type','application/json');return new Request(`https://preview.example${path}`,{...init,headers});};
async function setup():Promise<{sql:Database;env:CloudflareEnv}>{
  const SQL=await initSqlJs();const sql=new SQL.Database();sql.run('PRAGMA foreign_keys=ON');
  for(const name of ['0001_cf_foundation.sql','0001_cf02_preview_drafts.sql','0002_cf03_preview_evidence.sql','0003_cf04_preview_auth.sql','0004_cf05_google_drive.sql','0005_cf06_case_operations.sql'])sql.exec(migration(name));
  const now=new Date().toISOString();const add=(id:string,login:string,roles:string)=>sql.run('INSERT INTO preview_users VALUES (?,?,?,?,?,?,?,?,1,?)',[id,login,'1'.repeat(32),'2'.repeat(64),100000,login,`${login}@example.invalid`,roles,now]);
  add(ADMIN_ID,'admin','["admin"]');sql.exec(migration('0010_cf10_product_experience.sql'));add(STAFF_ID,'staff','["staff"]');sql.exec(migration('0020_cf28_workspace_settings.sql'));
  for(const [token,id]of[[ADMIN_TOKEN,ADMIN_ID],[STAFF_TOKEN,STAFF_ID]]as const)sql.run('INSERT INTO preview_sessions VALUES (?,?,?,?)',[await sha256(token),id,now,new Date(Date.now()+3_600_000).toISOString()]);
  return{sql,env:{DB:new SqlD1(sql)as unknown as NonNullable<CloudflareEnv['DB']>}};
}

test('CF28 saves personal theme, font, scale, density, and motion preferences across restart',async()=>{const{sql,env}=await setup();const initial=await worker.fetch(request('/api/settings/preferences',STAFF_TOKEN),env);assert.equal(initial.status,200);assert.equal((await initial.json()as any).preferences.version,0);const payload={theme:'DARK',fontFamily:'NOTO_SANS_KR',fontScale:120,density:'COMPACT',reduceMotion:true,expectedVersion:0};const saved=await worker.fetch(request('/api/settings/preferences',STAFF_TOKEN,{method:'PUT',body:JSON.stringify(payload)}),env);assert.equal(saved.status,200);const body=await saved.json()as any;assert.deepEqual({...body.preferences,updatedAt:null},{theme:'DARK',fontFamily:'NOTO_SANS_KR',fontScale:120,density:'COMPACT',reduceMotion:true,version:1,updatedAt:null});const stale=await worker.fetch(request('/api/settings/preferences',STAFF_TOKEN,{method:'PUT',body:JSON.stringify(payload)}),env);assert.equal(stale.status,409);const exported=sql.export();const SQL=await initSqlJs();const restarted=new SQL.Database(exported);assert.deepEqual(restarted.exec('SELECT theme,font_family,font_scale,density,reduce_motion,version FROM preview_user_preferences')[0].values[0],['DARK','NOTO_SANS_KR',120,'COMPACT',1,1]);restarted.close();sql.close();});

test('CF28 separates Admin workspace, local AI, Hermes policy, and append-only history',async()=>{const{sql,env}=await setup();assert.equal((await worker.fetch(request('/api/settings/admin-workspace',STAFF_TOKEN),env)).status,403);const saved=await worker.fetch(request('/api/settings/admin-workspace',ADMIN_TOKEN,{method:'PUT',body:JSON.stringify({organizationName:'CONCOST Claim Center',localAiMode:'PRIVATE_SERVER_BRIDGE',memoryProvider:'HERMES_AGENT',memoryApprovalMode:'ADMIN_REVIEW',shortTermMemoryEnabled:true,longTermMemoryEnabled:true,expectedVersion:0})}),env);assert.equal(saved.status,200);const body=await saved.json()as any;assert.equal(body.runtime.localAi,'SERVER_BRIDGE_REQUIRED');assert.equal(body.runtime.hermes,'D1_HERMES_COMPATIBLE_V2');assert.equal(body.runtime.memoryLearning,'FEEDBACK_APPROVAL_RETRIEVAL_ACTIVE');assert.equal(sql.exec('SELECT COUNT(*) FROM preview_settings_history')[0].values[0][0],1);assert.throws(()=>sql.run(`UPDATE preview_workspace_settings SET updated_by='${STAFF_ID}',version=2,updated_at='2099-01-01T00:00:00Z'`),/active Admin|require Admin/u);assert.throws(()=>sql.run("UPDATE preview_settings_history SET snapshot_json='{}'"),/append-only/u);assert.throws(()=>sql.run('INSERT INTO preview_settings_history VALUES (?,?,?,?,?,?,?)',['99999999-9999-4999-8999-999999999999','WORKSPACE_POLICY','concost','{}',2,STAFF_ID,new Date().toISOString()]),/actor or owner/u);sql.close();});

test('CF28 settings gear opens a single settings route with personal/Admin controls and Drive switching',()=>{const shell=readFileSync(join(process.cwd(),'apps','web','src','layout','AppShell.tsx'),'utf8');const settings=readFileSync(join(process.cwd(),'apps','web','src','routes','PreviewSettings.tsx'),'utf8');const drive=readFileSync(join(process.cwd(),'apps','web','src','routes','PreviewEvidenceHub.tsx'),'utf8');assert.match(shell,/개인 및 관리자 설정 열기/u);assert.match(shell,/label:\s*'설정'/u);assert.match(settings,/개인 설정/u);assert.match(settings,/관리자 설정/u);assert.doesNotMatch(settings,/내 화면 맞춤 설정/u);assert.match(settings,/개인 Gemini 연결 설정/u);assert.match(settings,/API KEY 발급방법/u);assert.match(settings,/로컬 AI 정책/u);assert.match(settings,/Hermes Memory 정책/u);assert.match(settings,/AI Memory 관리/u);assert.match(drive,/현재 회사 Drive 계정/u);assert.match(drive,/연결 계정 변경/u);assert.doesNotMatch(settings,/API Key[^\n]*value=\{[^}]*apiKey/u);});
