import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import initSqlJs, { type Database } from 'sql.js';
import worker, { type CloudflareEnv } from '../apps/cloudflare/src/index.js';

const ADMIN_ID='00000000-0000-4000-8000-000000000001';
const STAFF_ID='00000000-0000-4000-8000-000000000002';
const STAFF_TOKEN='cf35-staff-session-token';
async function sha256(value:string):Promise<string>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
class SqlStatement{private values:unknown[]=[];constructor(private readonly database:Database,private readonly sql:string){}bind(...values:unknown[]):SqlStatement{this.values=values;return this;}async first<T>():Promise<T|null>{const statement=this.database.prepare(this.sql);try{statement.bind(this.values as any[]);return statement.step()?statement.getAsObject()as T:null;}finally{statement.free();}}async all<T>():Promise<{results:T[]}>{const statement=this.database.prepare(this.sql);const results:T[]=[];try{statement.bind(this.values as any[]);while(statement.step())results.push(statement.getAsObject()as T);return{results};}finally{statement.free();}}async run():Promise<{success:boolean;meta:{changes:number;last_row_id:number}}>{this.database.run(this.sql,this.values as any[]);return{success:true,meta:{changes:this.database.getRowsModified(),last_row_id:0}};}}
class SqlD1{constructor(readonly database:Database){}prepare(sql:string):SqlStatement{return new SqlStatement(this.database,sql);}async batch(statements:SqlStatement[]):Promise<unknown[]>{this.database.run('BEGIN IMMEDIATE');try{const results=[];for(const statement of statements)results.push(await statement.run());this.database.run('COMMIT');return results;}catch(error){this.database.run('ROLLBACK');throw error;}}}
const migration=(name:string)=>readFileSync(join(process.cwd(),'apps','cloudflare','migrations',name),'utf8');
const request=(path:string,token='',init:RequestInit={})=>{const headers=new Headers(init.headers);if(token)headers.set('X-Session-Token',token);if(init.body)headers.set('Content-Type','application/json');return new Request(`https://preview.example${path}`,{...init,headers});};
async function setup():Promise<{sql:Database;env:CloudflareEnv}>{const SQL=await initSqlJs();const sql=new SQL.Database();sql.run('PRAGMA foreign_keys=ON');for(const name of ['0001_cf_foundation.sql','0001_cf02_preview_drafts.sql','0002_cf03_preview_evidence.sql','0003_cf04_preview_auth.sql','0004_cf05_google_drive.sql','0005_cf06_case_operations.sql'])sql.exec(migration(name));const now=new Date().toISOString();const add=(id:string,login:string,roles:string)=>sql.run('INSERT INTO preview_users VALUES (?,?,?,?,?,?,?,?,1,?)',[id,login,'1'.repeat(32),'2'.repeat(64),100000,login,`${login}@example.invalid`,roles,now]);add(ADMIN_ID,'admin','["admin"]');sql.exec(migration('0010_cf10_product_experience.sql'));add(STAFF_ID,'staff','["staff"]');sql.exec(migration('0027_cf35_guided_workspace.sql'));sql.run('INSERT INTO preview_sessions VALUES (?,?,?,?)',[await sha256(STAFF_TOKEN),STAFF_ID,now,new Date(Date.now()+3_600_000).toISOString()]);return{sql,env:{DB:new SqlD1(sql)as unknown as NonNullable<CloudflareEnv['DB']>}};}

test('CF35 persists each user tutorial completion with optimistic concurrency and immutable history',async()=>{const{sql,env}=await setup();assert.equal((await worker.fetch(request('/api/settings/tutorial'),env)).status,401);const initial=await worker.fetch(request('/api/settings/tutorial',STAFF_TOKEN),env);assert.equal(initial.status,200);assert.deepEqual((await initial.json()as any).tutorial,{completedTutorialVersion:null,completedAt:null,version:0,updatedAt:null});const completed=await worker.fetch(request('/api/settings/tutorial',STAFF_TOKEN,{method:'PUT',body:JSON.stringify({tutorialVersion:'CF35_V1',expectedVersion:0})}),env);assert.equal(completed.status,200);const body=await completed.json()as any;assert.equal(body.tutorial.completedTutorialVersion,'CF35_V1');assert.equal(body.tutorial.version,1);assert.equal(sql.exec('SELECT COUNT(*) FROM preview_user_tutorial_history')[0].values[0][0],1);const replay=await worker.fetch(request('/api/settings/tutorial',STAFF_TOKEN,{method:'PUT',body:JSON.stringify({tutorialVersion:'CF35_V1',expectedVersion:1})}),env);assert.equal(replay.status,200);assert.equal(sql.exec('SELECT COUNT(*) FROM preview_user_tutorial_history')[0].values[0][0],1);const stale=await worker.fetch(request('/api/settings/tutorial',STAFF_TOKEN,{method:'PUT',body:JSON.stringify({tutorialVersion:'CF36_V1',expectedVersion:0})}),env);assert.equal(stale.status,409);assert.throws(()=>sql.run("UPDATE preview_user_tutorial_history SET tutorial_version='CF99_V1'"),/append-only/u);assert.throws(()=>sql.run(`UPDATE preview_user_tutorial_state SET updated_by='${ADMIN_ID}',version=2,completed_at='2099-01-01T00:00:00Z',updated_at='2099-01-01T00:00:00Z'`),/active owner|identity|optimistic/u);const exported=sql.export();const SQL=await initSqlJs();const restarted=new SQL.Database(exported);assert.equal(restarted.exec('SELECT completed_tutorial_version,version FROM preview_user_tutorial_state')[0].values[0].join(':'),'CF35_V1:1');restarted.close();sql.close();});

test('CF79 offers a renewed first-run walkthrough and current high-density help on every screen',()=>{const shell=readFileSync('apps/web/src/layout/AppShell.tsx','utf8');const guide=readFileSync('apps/web/src/layout/WorkspaceHelpCenter.tsx','utf8');const content=readFileSync('apps/web/src/layout/workspace-help-content.ts','utf8');const css=readFileSync('apps/web/src/layout/WorkspaceHelpCenter.css','utf8');const theme=readFileSync('apps/web/src/theme-system.css','utf8');assert.match(shell,/WorkspaceHelpCenter/u);assert.match(guide,/처음 사용하는 분을 위한 클레임센터 업무 순서/u);assert.match(guide,/현재 화면 도움말 열기/u);assert.match(guide,/전체 튜토리얼 다시 보기/u);assert.match(guide,/주황색으로 확대된 기능을 직접 눌러야/u);assert.match(guide,/scrollIntoView/u);assert.match(guide,/workspace-tutorial-focus-source/u);assert.match(guide,/api\/settings\/tutorial/u);assert.match(content,/WORKSPACE_TUTORIAL_STEPS/u);for(const marker of ['전 회원 공유 목록','챕터별 담당자 지정','Drive 저장·인맥 등록','납품완료 표시','Ctrl\\+S','HWP\/DOCX\/PDF','한국\/베트남 휴일'])assert.match(content,new RegExp(marker,'u'));for(const routeId of ['CONTACT-01','CONTACT-02','CONTACT-03'])assert.match(content,new RegExp(`'${routeId}'`,'u'));assert.match(content,/ROUTE_HELP/u);for(const category of ['home','proposal','work','library','court','quality','settings'])assert.match(content,new RegExp(`${category}:`));for(const marker of ['workspace-tutorial-shade','workspace-tutorial-target','workspace-tutorial-coach.is-launcher'])assert.match(css,new RegExp(marker,'u'));assert.ok(css.includes('@media (max-width: 760px)'));assert.match(shell,/label: 'HOME', eyebrow: '클레임센터 홈'/u);assert.doesNotMatch(shell,/\{group\.eyebrow\}/u);assert.doesNotMatch(shell,/PROJECT INTAKE & AWARD|PROJECT WORK|EVIDENCE LIBRARY|COURT & LITIGATION|QUALITY & DELIVERY/u);assert.match(theme,/data-nav-subgroup='intake'/u);assert.match(theme,/data-nav-subgroup='proposal'/u);});

test('CF35 developer handoff fixes the private bridge trust boundary and report wizard remains one-step-at-a-time',()=>{const handoff=readFileSync('docs/runbooks/vietnam-hermes-private-bridge.md','utf8');const studio=readFileSync('apps/web/src/routes/PreviewReportStudio.tsx','utf8');for(const marker of ['D1이 기억 후보','X-Claim-Signature','HERMES_PRIVATE_BRIDGE_V1','필수 적대 테스트','인수인계 완료 기준'])assert.match(handoff,new RegExp(marker));for(const marker of ['type ReportWizardStep = 1 | 2 | 3 | 4 | 5','stepUnlocked','이 단계 완료 · 다음 단계','목차 확정 · 다음 단계','챕터별 자동작성(권장)','저장된 최신본 검토 요청','downloadFinalReport','downloadFinalDocument'])assert.ok(studio.includes(marker),`missing report contract: ${marker}`);});
